spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: NewPassword123!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true






